package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * AlicuotasId generated by hbm2java
 */
public class AlicuotasId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5055357627747146057L;
	private int codAlic;
	private String codMuest;
	private String codEst;

	public AlicuotasId() {
	}

	public AlicuotasId(int codAlic, String codMuest, String codEst) {
		this.codAlic = codAlic;
		this.codMuest = codMuest;
		this.codEst = codEst;
	}

	public int getCodAlic() {
		return this.codAlic;
	}

	public void setCodAlic(int codAlic) {
		this.codAlic = codAlic;
	}

	public String getCodMuest() {
		return this.codMuest;
	}

	public void setCodMuest(String codMuest) {
		this.codMuest = codMuest;
	}

	public String getCodEst() {
		return this.codEst;
	}

	public void setCodEst(String codEst) {
		this.codEst = codEst;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlicuotasId))
			return false;
		AlicuotasId castOther = (AlicuotasId) other;

		return (this.getCodAlic() == castOther.getCodAlic())
				&& ((this.getCodMuest() == castOther.getCodMuest()) || (this
						.getCodMuest() != null
						&& castOther.getCodMuest() != null && this
						.getCodMuest().equals(castOther.getCodMuest())))
				&& ((this.getCodEst() == castOther.getCodEst()) || (this
						.getCodEst() != null && castOther.getCodEst() != null && this
						.getCodEst().equals(castOther.getCodEst())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodAlic();
		result = 37 * result
				+ (getCodMuest() == null ? 0 : this.getCodMuest().hashCode());
		result = 37 * result
				+ (getCodEst() == null ? 0 : this.getCodEst().hashCode());
		return result;
	}

}
