package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 15, 2012 2:46:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * CajaId generated by hbm2java
 */
public class CajaId implements java.io.Serializable {

	private static final long serialVersionUID = -9061941318963384859L;
	private String codCaja;
	private String ccodRack;

	public CajaId() {
	}

	public CajaId(String codCaja, String ccodRack) {
		this.codCaja = codCaja;
		this.ccodRack = ccodRack;
	}

	public String getCodCaja() {
		return this.codCaja;
	}

	public void setCodCaja(String codCaja) {
		this.codCaja = codCaja;
	}

	public String getCcodRack() {
		return this.ccodRack;
	}

	public void setCcodRack(String ccodRack) {
		this.ccodRack = ccodRack;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CajaId))
			return false;
		CajaId castOther = (CajaId) other;

		return ((this.getCodCaja() == castOther.getCodCaja()) || (this
				.getCodCaja() != null && castOther.getCodCaja() != null && this
				.getCodCaja().equals(castOther.getCodCaja())))
				&& ((this.getCcodRack() == castOther.getCcodRack()) || (this
						.getCcodRack() != null
						&& castOther.getCcodRack() != null && this
						.getCcodRack().equals(castOther.getCcodRack())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodCaja() == null ? 0 : this.getCodCaja().hashCode());
		result = 37 * result
				+ (getCcodRack() == null ? 0 : this.getCcodRack().hashCode());
		return result;
	}

}
