package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 15, 2012 2:46:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Caja generated by hbm2java
 */
public class Caja implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5690031411128721488L;
	
	private CajaId id;
	private int posRack;
	private String usoAlic;
	private String tipMues;
	private Date feIni;
	private Date feFin;
	private int tempAlm;
	private String uso;
	private int capAlm;
	private String posNeg;
	private String estudio;
	
	public Caja(){
		
	}

	public Caja(CajaId id) {
		this.id =id;
	}

	public Caja(CajaId id, int posRack, String usoAlic, String tipMues,
			Date feIni, Date feFin, int tempAlm, String uso, int capAlm,
			String posNeg) {
		this.id = id;
		this.posRack = posRack;
		this.usoAlic = usoAlic;
		this.tipMues = tipMues;
		this.feIni = feIni;
		this.feFin = feFin;
		this.tempAlm = tempAlm;
		this.uso = uso;
		this.capAlm = capAlm;
		this.posNeg = posNeg;
	}

	public CajaId getId() {
		return this.id;
	}

	public void setId(CajaId id) {
		this.id = id;
	}

	public int getPosRack() {
		return this.posRack;
	}

	public void setPosRack(int posRack) {
		this.posRack = posRack;
	}

	public String getUsoAlic() {
		return this.usoAlic;
	}

	public void setUsoAlic(String usoAlic) {
		this.usoAlic = usoAlic;
	}

	public String getTipMues() {
		return this.tipMues;
	}

	public void setTipMues(String tipMues) {
		this.tipMues = tipMues;
	}

	public Date getFeIni() {
		return this.feIni;
	}

	public void setFeIni(Date feIni) {
		this.feIni = feIni;
	}

	public Date getFeFin() {
		return this.feFin;
	}

	public void setFeFin(Date feFin) {
		this.feFin = feFin;
	}

	public int getTempAlm() {
		return this.tempAlm;
	}

	public void setTempAlm(int tempAlm) {
		this.tempAlm = tempAlm;
	}

	public String getUso() {
		return this.uso;
	}

	public void setUso(String uso) {
		this.uso = uso;
	}

	public int getCapAlm() {
		return this.capAlm;
	}

	public void setCapAlm(int capAlm) {
		this.capAlm = capAlm;
	}

	public String getPosNeg() {
		return this.posNeg;
	}

	public void setPosNeg(String posNeg) {
		this.posNeg = posNeg;
	}

	public String getEstudio() {
		return estudio;
	}

	public void setEstudio(String estudio) {
		this.estudio = estudio;
	}
	
	

}
