package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 3, 2012 1:14:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * CatAlicuotas generated by hbm2java
 */
public class CatAlicuotas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2374687678699207495L;
	private CatAlicuotasId id;
	private String sepUso;
	private int tempAlm;
	private int volPerm;
	private String muestPert;

	public CatAlicuotas() {
	}

	public CatAlicuotas(CatAlicuotasId id, String sepUso, int tempAlm,
			int volPerm, String muestPert) {
		this.id = id;
		this.sepUso = sepUso;
		this.tempAlm = tempAlm;
		this.volPerm = volPerm;
		this.muestPert = muestPert;
	}

	public CatAlicuotasId getId() {
		return this.id;
	}

	public void setId(CatAlicuotasId id) {
		this.id = id;
	}

	public String getSepUso() {
		return this.sepUso;
	}

	public void setSepUso(String sepUso) {
		this.sepUso = sepUso;
	}

	public int getTempAlm() {
		return this.tempAlm;
	}

	public void setTempAlm(int tempAlm) {
		this.tempAlm = tempAlm;
	}

	public int getVolPerm() {
		return this.volPerm;
	}

	public void setVolPerm(int volPerm) {
		this.volPerm = volPerm;
	}

	public String getMuestPert() {
		return this.muestPert;
	}

	public void setMuestPert(String muestPert) {
		this.muestPert = muestPert;
	}

}
