package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * DetParamId generated by hbm2java
 */
public class DetParamId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 373720072067053676L;
	private String codItem;
	private String codCat;

	public DetParamId() {
	}

	public DetParamId(String codItem, String codCat) {
		this.codItem = codItem;
		this.codCat = codCat;
	}

	public String getCodItem() {
		return this.codItem;
	}

	public void setCodItem(String codItem) {
		this.codItem = codItem;
	}

	public String getCodCat() {
		return this.codCat;
	}

	public void setCodCat(String codCat) {
		this.codCat = codCat;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetParamId))
			return false;
		DetParamId castOther = (DetParamId) other;

		return ((this.getCodItem() == castOther.getCodItem()) || (this
				.getCodItem() != null && castOther.getCodItem() != null && this
				.getCodItem().equals(castOther.getCodItem())))
				&& ((this.getCodCat() == castOther.getCodCat()) || (this
						.getCodCat() != null && castOther.getCodCat() != null && this
						.getCodCat().equals(castOther.getCodCat())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodItem() == null ? 0 : this.getCodItem().hashCode());
		result = 37 * result
				+ (getCodCat() == null ? 0 : this.getCodCat().hashCode());
		return result;
	}

}
