package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * DetrAlicId generated by hbm2java
 */
public class DetrAlicId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4099924490854368712L;
	private String codAlic;
	private String codReg;

	public DetrAlicId() {
	}

	public DetrAlicId(String codAlic, String codReg) {
		this.codAlic = codAlic;
		this.codReg = codReg;
	}

	public String getCodAlic() {
		return this.codAlic;
	}

	public void setCodAlic(String codAlic) {
		this.codAlic = codAlic;
	}

	public String getCodReg() {
		return this.codReg;
	}

	public void setCodReg(String codReg) {
		this.codReg = codReg;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetrAlicId))
			return false;
		DetrAlicId castOther = (DetrAlicId) other;

		return ((this.getCodAlic() == castOther.getCodAlic()) || (this
				.getCodAlic() != null && castOther.getCodAlic() != null && this
				.getCodAlic().equals(castOther.getCodAlic())))
				&& ((this.getCodReg() == castOther.getCodReg()) || (this
						.getCodReg() != null && castOther.getCodReg() != null && this
						.getCodReg().equals(castOther.getCodReg())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodAlic() == null ? 0 : this.getCodAlic().hashCode());
		result = 37 * result
				+ (getCodReg() == null ? 0 : this.getCodReg().hashCode());
		return result;
	}

}
