package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * DetrAlic generated by hbm2java
 */
public class DetrAlic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2444204165181254025L;
	private DetrAlicId id;
	private String volAlic;
	private String posAlic;
	private String tipAlic;
	private String obsAlic;
	private String tipMuestr;
	private String tipEstudio;

	public DetrAlic() {
	}

	public DetrAlic(DetrAlicId id) {
		this.id = id;
	}

	public DetrAlic(DetrAlicId id, String volAlic, String posAlic,
			String tipAlic, String obsAlic, String tipMuestr, String tipEstudio) {
		this.id = id;
		this.volAlic = volAlic;
		this.posAlic = posAlic;
		this.tipAlic = tipAlic;
		this.obsAlic = obsAlic;
		this.tipMuestr = tipMuestr;
		this.tipEstudio = tipEstudio;
	}

	public DetrAlicId getId() {
		return this.id;
	}

	public void setId(DetrAlicId id) {
		this.id = id;
	}

	public String getVolAlic() {
		return this.volAlic;
	}

	public void setVolAlic(String volAlic) {
		this.volAlic = volAlic;
	}

	public String getPosAlic() {
		return this.posAlic;
	}

	public void setPosAlic(String posAlic) {
		this.posAlic = posAlic;
	}

	public String getTipAlic() {
		return this.tipAlic;
	}

	public void setTipAlic(String tipAlic) {
		this.tipAlic = tipAlic;
	}

	public String getObsAlic() {
		return this.obsAlic;
	}

	public void setObsAlic(String obsAlic) {
		this.obsAlic = obsAlic;
	}

	public String getTipMuestr() {
		return this.tipMuestr;
	}

	public void setTipMuestr(String tipMuestr) {
		this.tipMuestr = tipMuestr;
	}

	public String getTipEstudio() {
		return this.tipEstudio;
	}

	public void setTipEstudio(String tipEstudio) {
		this.tipEstudio = tipEstudio;
	}

}
