package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EncrAlic generated by hbm2java
 */
public class EncrAlic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5266844492869356001L;
	private String codReg;
	private int userReg;
	private Date datiReg;
	private String cajaReg;
	private int rack;
	private int freezer;

	public EncrAlic() {
	}

	public EncrAlic(String codReg, int userReg, Date datiReg, String cajaReg,
			int rack, int freezer) {
		this.codReg = codReg;
		this.userReg = userReg;
		this.datiReg = datiReg;
		this.cajaReg = cajaReg;
		this.rack = rack;
		this.freezer = freezer;
	}

	public String getCodReg() {
		return this.codReg;
	}

	public void setCodReg(String codReg) {
		this.codReg = codReg;
	}

	public int getUserReg() {
		return this.userReg;
	}

	public void setUserReg(int userReg) {
		this.userReg = userReg;
	}

	public Date getDatiReg() {
		return this.datiReg;
	}

	public void setDatiReg(Date datiReg) {
		this.datiReg = datiReg;
	}

	public String getCajaReg() {
		return this.cajaReg;
	}

	public void setCajaReg(String cajaReg) {
		this.cajaReg = cajaReg;
	}

	public int getRack() {
		return this.rack;
	}

	public void setRack(int rack) {
		this.rack = rack;
	}

	public int getFreezer() {
		return this.freezer;
	}

	public void setFreezer(int freezer) {
		this.freezer = freezer;
	}

}
