package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 12, 2012 8:55:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Freezer generated by hbm2java
 */
public class Freezer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6408837765809019952L;
	private int codFreezer;
	private Date feinivig;
	private Date fefinvig;
	private int tempMin;
	private int tempMax;
	private String usoAlm;
	private int capAlm;
	private String tipAlm;
	private String motClose;
	private String equipSerie;
	private String equipModelo;
	private String indCalib;
	private String serieTerm;
	private String nameResp;
	private int nroFila;
	private int nroColumn;

	public Freezer() {
	}

	public Freezer(int codFreezer, Date feinivig, Date fefinvig, int tempMin,
			int tempMax, String usoAlm, int capAlm, String tipAlm,
			String equipSerie, String equipModelo, String indCalib,
			String nameResp, int nroFila, int nroColumn) {
		this.codFreezer = codFreezer;
		this.feinivig = feinivig;
		this.fefinvig = fefinvig;
		this.tempMin = tempMin;
		this.tempMax = tempMax;
		this.usoAlm = usoAlm;
		this.capAlm = capAlm;
		this.tipAlm = tipAlm;
		this.equipSerie = equipSerie;
		this.equipModelo = equipModelo;
		this.indCalib = indCalib;
		this.nameResp = nameResp;
		this.nroFila = nroFila;
		this.nroColumn = nroColumn;
	}

	public Freezer(int codFreezer, Date feinivig, Date fefinvig, int tempMin,
			int tempMax, String usoAlm, int capAlm, String tipAlm,
			String motClose, String equipSerie, String equipModelo,
			String indCalib, String serieTerm, String nameResp, int nroFila,
			int nroColumn) {
		this.codFreezer = codFreezer;
		this.feinivig = feinivig;
		this.fefinvig = fefinvig;
		this.tempMin = tempMin;
		this.tempMax = tempMax;
		this.usoAlm = usoAlm;
		this.capAlm = capAlm;
		this.tipAlm = tipAlm;
		this.motClose = motClose;
		this.equipSerie = equipSerie;
		this.equipModelo = equipModelo;
		this.indCalib = indCalib;
		this.serieTerm = serieTerm;
		this.nameResp = nameResp;
		this.nroFila = nroFila;
		this.nroColumn = nroColumn;
	}

	public int getCodFreezer() {
		return this.codFreezer;
	}

	public void setCodFreezer(int codFreezer) {
		this.codFreezer = codFreezer;
	}

	public Date getFeinivig() {
		return this.feinivig;
	}

	public void setFeinivig(Date feinivig) {
		this.feinivig = feinivig;
	}

	public Date getFefinvig() {
		return this.fefinvig;
	}

	public void setFefinvig(Date fefinvig) {
		this.fefinvig = fefinvig;
	}

	public int getTempMin() {
		return this.tempMin;
	}

	public void setTempMin(int tempMin) {
		this.tempMin = tempMin;
	}

	public int getTempMax() {
		return this.tempMax;
	}

	public void setTempMax(int tempMax) {
		this.tempMax = tempMax;
	}

	public String getUsoAlm() {
		return this.usoAlm;
	}

	public void setUsoAlm(String usoAlm) {
		this.usoAlm = usoAlm;
	}

	public int getCapAlm() {
		return this.capAlm;
	}

	public void setCapAlm(int capAlm) {
		this.capAlm = capAlm;
	}

	public String getTipAlm() {
		return this.tipAlm;
	}

	public void setTipAlm(String tipAlm) {
		this.tipAlm = tipAlm;
	}

	public String getMotClose() {
		return this.motClose;
	}

	public void setMotClose(String motClose) {
		this.motClose = motClose;
	}

	public String getEquipSerie() {
		return this.equipSerie;
	}

	public void setEquipSerie(String equipSerie) {
		this.equipSerie = equipSerie;
	}

	public String getEquipModelo() {
		return this.equipModelo;
	}

	public void setEquipModelo(String equipModelo) {
		this.equipModelo = equipModelo;
	}

	public String getIndCalib() {
		return this.indCalib;
	}

	public void setIndCalib(String indCalib) {
		this.indCalib = indCalib;
	}

	public String getSerieTerm() {
		return this.serieTerm;
	}

	public void setSerieTerm(String serieTerm) {
		this.serieTerm = serieTerm;
	}

	public String getNameResp() {
		return this.nameResp;
	}

	public void setNameResp(String nameResp) {
		this.nameResp = nameResp;
	}

	public int getNroFila() {
		return this.nroFila;
	}

	public void setNroFila(int nroFila) {
		this.nroFila = nroFila;
	}

	public int getNroColumn() {
		return this.nroColumn;
	}

	public void setNroColumn(int nroColumn) {
		this.nroColumn = nroColumn;
	}

}
