package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * ListParam generated by hbm2java
 */
public class ListParam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3415572278343197724L;
	private String codCat;
	private String descList;
	private int ordeList;

	public ListParam() {
	}

	public ListParam(String codCat, String descList, int ordeList) {
		this.codCat = codCat;
		this.descList = descList;
		this.ordeList = ordeList;
	}

	public String getCodCat() {
		return this.codCat;
	}

	public void setCodCat(String codCat) {
		this.codCat = codCat;
	}

	public String getDescList() {
		return this.descList;
	}

	public void setDescList(String descList) {
		this.descList = descList;
	}

	public int getOrdeList() {
		return this.ordeList;
	}

	public void setOrdeList(int ordeList) {
		this.ordeList = ordeList;
	}

}
