package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Menline generated by hbm2java
 */
public class Menline implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3564183526706422713L;
	private MenlineId id;
	private String descMen;
	private String tipLine;

	public Menline() {
	}

	public Menline(MenlineId id, String descMen, String tipLine) {
		this.id = id;
		this.descMen = descMen;
		this.tipLine = tipLine;
	}

	public MenlineId getId() {
		return this.id;
	}

	public void setId(MenlineId id) {
		this.id = id;
	}

	public String getDescMen() {
		return this.descMen;
	}

	public void setDescMen(String descMen) {
		this.descMen = descMen;
	}

	public String getTipLine() {
		return this.tipLine;
	}

	public void setTipLine(String tipLine) {
		this.tipLine = tipLine;
	}

}
