package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Menprinc generated by hbm2java
 */
public class Menprinc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -50450098150072352L;
	private String codMen;
	private String descMen;

	public Menprinc() {
	}

	public Menprinc(String codMen, String descMen) {
		this.codMen = codMen;
		this.descMen = descMen;
	}

	public String getCodMen() {
		return this.codMen;
	}

	public void setCodMen(String codMen) {
		this.codMen = codMen;
	}

	public String getDescMen() {
		return this.descMen;
	}

	public void setDescMen(String descMen) {
		this.descMen = descMen;
	}

}
