package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Messages generated by hbm2java
 */
public class Messages implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8469489454247291454L;
	private int mid;
	private String description;
	private String typeMsn;

	public Messages() {
	}

	public Messages(int mid, String description, String typeMsn) {
		this.mid = mid;
		this.description = description;
		this.typeMsn = typeMsn;
	}

	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTypeMsn() {
		return this.typeMsn;
	}

	public void setTypeMsn(String typeMsn) {
		this.typeMsn = typeMsn;
	}

}
