package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Oct 31, 2012 11:12:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Password generated by hbm2java
 */
public class Password implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4027769712594341717L;
	private String passCoduser;
	private String passIndblan;
	private Date passDtblan;
	private String passMd5;

	public Password() {
	}

	public Password(String passCoduser, String passIndblan, Date passDtblan,
			String passMd5) {
		this.passCoduser = passCoduser;
		this.passIndblan = passIndblan;
		this.passDtblan = passDtblan;
		this.passMd5 = passMd5;
	}

	public String getPassCoduser() {
		return this.passCoduser;
	}

	public void setPassCoduser(String passCoduser) {
		this.passCoduser = passCoduser;
	}

	public String getPassIndblan() {
		return this.passIndblan;
	}

	public void setPassIndblan(String passIndblan) {
		this.passIndblan = passIndblan;
	}

	public Date getPassDtblan() {
		return this.passDtblan;
	}

	public void setPassDtblan(Date passDtblan) {
		this.passDtblan = passDtblan;
	}

	public String getPassMd5() {
		return this.passMd5;
	}

	public void setPassMd5(String passMd5) {
		this.passMd5 = passMd5;
	}

}
