package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 2, 2012 9:29:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Patron generated by hbm2java
 */
public class Patron implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codPatron;
	private String patron;
	private String descripcion;

	public Patron() {
	}

	public Patron(String codPatron, String patron, String descripcion) {
		this.codPatron = codPatron;
		this.patron = patron;
		this.descripcion = descripcion;
	}

	public String getCodPatron() {
		return this.codPatron;
	}

	public void setCodPatron(String codPatron) {
		this.codPatron = codPatron;
	}

	public String getPatron() {
		return this.patron;
	}

	public void setPatron(String patron) {
		this.patron = patron;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
