package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8536341819088098646L;
	private String codPerf;
	private String descPerf;
	private Date finiVig;
	private Date ffinVig;

	public Perfil() {
	}

	public Perfil(String codPerf, String descPerf, Date finiVig, Date ffinVig) {
		this.codPerf = codPerf;
		this.descPerf = descPerf;
		this.finiVig = finiVig;
		this.ffinVig = ffinVig;
	}

	public String getCodPerf() {
		return this.codPerf;
	}

	public void setCodPerf(String codPerf) {
		this.codPerf = codPerf;
	}

	public String getDescPerf() {
		return this.descPerf;
	}

	public void setDescPerf(String descPerf) {
		this.descPerf = descPerf;
	}

	public Date getFiniVig() {
		return this.finiVig;
	}

	public void setFiniVig(Date finiVig) {
		this.finiVig = finiVig;
	}

	public Date getFfinVig() {
		return this.ffinVig;
	}

	public void setFfinVig(Date ffinVig) {
		this.ffinVig = ffinVig;
	}

}
