package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * PerfTransacId generated by hbm2java
 */
public class PerfTransacId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -850719865260313794L;
	private String codTrans;
	private String codPerf;

	public PerfTransacId() {
	}

	public PerfTransacId(String codTrans, String codPerf) {
		this.codTrans = codTrans;
		this.codPerf = codPerf;
	}

	public String getCodTrans() {
		return this.codTrans;
	}

	public void setCodTrans(String codTrans) {
		this.codTrans = codTrans;
	}

	public String getCodPerf() {
		return this.codPerf;
	}

	public void setCodPerf(String codPerf) {
		this.codPerf = codPerf;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfTransacId))
			return false;
		PerfTransacId castOther = (PerfTransacId) other;

		return ((this.getCodTrans() == castOther.getCodTrans()) || (this
				.getCodTrans() != null && castOther.getCodTrans() != null && this
				.getCodTrans().equals(castOther.getCodTrans())))
				&& ((this.getCodPerf() == castOther.getCodPerf()) || (this
						.getCodPerf() != null && castOther.getCodPerf() != null && this
						.getCodPerf().equals(castOther.getCodPerf())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodTrans() == null ? 0 : this.getCodTrans().hashCode());
		result = 37 * result
				+ (getCodPerf() == null ? 0 : this.getCodPerf().hashCode());
		return result;
	}

}
