package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PerfTransac generated by hbm2java
 */
public class PerfTransac implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 215502792788672960L;
	private PerfTransacId id;
	private Date feiniVig;
	private Date fefinVig;

	public PerfTransac() {
	}

	public PerfTransac(PerfTransacId id, Date feiniVig, Date fefinVig) {
		this.id = id;
		this.feiniVig = feiniVig;
		this.fefinVig = fefinVig;
	}

	public PerfTransacId getId() {
		return this.id;
	}

	public void setId(PerfTransacId id) {
		this.id = id;
	}

	public Date getFeiniVig() {
		return this.feiniVig;
	}

	public void setFeiniVig(Date feiniVig) {
		this.feiniVig = feiniVig;
	}

	public Date getFefinVig() {
		return this.fefinVig;
	}

	public void setFefinVig(Date fefinVig) {
		this.fefinVig = fefinVig;
	}

}
