package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 15, 2012 1:54:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Rack generated by hbm2java
 */
public class Rack implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3024181108336076196L;
	private RackId id;
	private Integer capAlm;
	private Date feIni;
	private Date feFin;
	private Integer posFreezer;

	public Rack() {
	}

	public Rack(RackId id) {
		this.id = id;
	}

	public Rack(RackId id, Integer capAlm, Date feIni, Date feFin,
			Integer posFreezer) {
		this.id = id;
		this.capAlm = capAlm;
		this.feIni = feIni;
		this.feFin = feFin;
		this.posFreezer = posFreezer;
	}

	public RackId getId() {
		return this.id;
	}

	public void setId(RackId id) {
		this.id = id;
	}

	public Integer getCapAlm() {
		return this.capAlm;
	}

	public void setCapAlm(Integer capAlm) {
		this.capAlm = capAlm;
	}

	public Date getFeIni() {
		return this.feIni;
	}

	public void setFeIni(Date feIni) {
		this.feIni = feIni;
	}

	public Date getFeFin() {
		return this.feFin;
	}

	public void setFeFin(Date feFin) {
		this.feFin = feFin;
	}

	public Integer getPosFreezer() {
		return this.posFreezer;
	}

	public void setPosFreezer(Integer posFreezer) {
		this.posFreezer = posFreezer;
	}

}
