package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 15, 2012 9:23:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;



/**
 * RegAlic generated by hbm2java
 */
public class RegAlic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6890416469363700411L;
	private RegAlicId id;
	private int codFreezer;
	private String codRack;
	private int codBox;
	private String negPos;
	private Float volAlic;
	private Float pesoAlic;
	private String tipo;
	private String condicion;
	private String separada;
	private Date fehorReg;
	private String codUser;
	private int numDes;
	

	public RegAlic() {
	}

	public RegAlic(RegAlicId id, int codFreezer, String codRack, int codBox,
			String negPos, Date fehorReg, String codUser) {
		this.id = id;
		this.codFreezer = codFreezer;
		this.codRack = codRack;
		this.codBox = codBox;
		this.negPos = negPos;
		this.fehorReg = fehorReg;
		this.codUser = codUser;
	}

	public RegAlicId getId() {
		return this.id;
	}

	public void setId(RegAlicId id) {
		this.id = id;
	}

	public int getCodFreezer() {
		return this.codFreezer;
	}

	public void setCodFreezer(int codFreezer) {
		this.codFreezer = codFreezer;
	}

	public String getCodRack() {
		return this.codRack;
	}

	public void setCodRack(String codRack) {
		this.codRack = codRack;
	}

	public int getCodBox() {
		return this.codBox;
	}

	public void setCodBox(int codBox) {
		this.codBox = codBox;
	}

	public String getNegPos() {
		return this.negPos;
	}

	public void setNegPos(String negPos) {
		this.negPos = negPos;
	}

	public Date getFehorReg() {
		return this.fehorReg;
	}

	public void setFehorReg(Date fehorReg) {
		this.fehorReg = fehorReg;
	}

	public String getCodUser() {
		return this.codUser;
	}

	public void setCodUser(String codUser) {
		this.codUser = codUser;
	}

	public Float getVolAlic() {
		return volAlic;
	}

	public void setVolAlic(Float volAlic) {
		this.volAlic = volAlic;
	}

	public Float getPesoAlic() {
		return pesoAlic;
	}

	public void setPesoAlic(Float pesoAlic) {
		this.pesoAlic = pesoAlic;
	}
	

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	

	public String getCondicion() {
		return condicion;
	}

	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}

	public String getSeparada() {
		return separada;
	}

	public void setSeparada(String separada) {
		this.separada = separada;
	}
	

	public int getNumDes() {
		return numDes;
	}

	public void setNumDes(int numDes) {
		this.numDes = numDes;
	}

	@Override
	public boolean equals(Object other) {
		
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegAlic))
			return false;
		
		RegAlic castOther = (RegAlic) other;

		return (this.getId().getCodAlic().equals(castOther.getId().getCodAlic()));
	}

}
