package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 29, 2012 6:12:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * RegDescarte generated by hbm2java
 */
public class RegDescarte implements java.io.Serializable {

	private static final long serialVersionUID = -1156518322045527040L;
	private RegDescarteId id;
	private String codUsr;

	public RegDescarte() {
	}

	public RegDescarte(RegDescarteId id, String codUsr) {
		this.id = id;
		this.codUsr = codUsr;
	}

	public RegDescarteId getId() {
		return this.id;
	}

	public void setId(RegDescarteId id) {
		this.id = id;
	}

	public String getCodUsr() {
		return this.codUsr;
	}

	public void setCodUsr(String codUsr) {
		this.codUsr = codUsr;
	}

}
