package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 29, 2012 6:12:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RegDescarteId generated by hbm2java
 */
public class RegDescarteId implements java.io.Serializable {


	private static final long serialVersionUID = -3428699759151373707L;
	private String codAlic;
	private Date fehorDesc;

	public RegDescarteId() {
	}

	public RegDescarteId(String codAlic, Date fehorDesc) {
		this.codAlic = codAlic;
		this.fehorDesc = fehorDesc;
	}

	public String getCodAlic() {
		return this.codAlic;
	}

	public void setCodAlic(String codAlic) {
		this.codAlic = codAlic;
	}

	public Date getFehorDesc() {
		return this.fehorDesc;
	}

	public void setFehorDesc(Date fehorDesc) {
		this.fehorDesc = fehorDesc;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegDescarteId))
			return false;
		RegDescarteId castOther = (RegDescarteId) other;

		return ((this.getCodAlic() == castOther.getCodAlic()) || (this
				.getCodAlic() != null && castOther.getCodAlic() != null && this
				.getCodAlic().equals(castOther.getCodAlic())))
				&& ((this.getFehorDesc() == castOther.getFehorDesc()) || (this
						.getFehorDesc() != null
						&& castOther.getFehorDesc() != null && this
						.getFehorDesc().equals(castOther.getFehorDesc())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodAlic() == null ? 0 : this.getCodAlic().hashCode());
		result = 37 * result
				+ (getFehorDesc() == null ? 0 : this.getFehorDesc().hashCode());
		return result;
	}

}
