package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Dec 19, 2012 12:05:15 PM by Hibernate Tools 3.4.0.CR1



/**
 * RegSepCohorte generated by hbm2java
 */
public class RegSepCohorte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7617192960549791172L;
	private String codigoLab;
	private Float volumen;

	public RegSepCohorte() {
	}

	public String getCodigoLab() {
		return codigoLab;
	}

	public void setCodigoLab(String codigoLab) {
		this.codigoLab = codigoLab;
	}

	public Float getVolumen() {
		return volumen;
	}

	public void setVolumen(Float volumen) {
		this.volumen = volumen;
	}

	
}
