package ni.gob.minsa.sistema.hibernate.bussines;

// Generated 08-07-2012 11:27:23 AM by Hibernate Tools 3.4.0.CR1

/**
 * Transacs generated by hbm2java
 */
public class Transacs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3084932129030641578L;
	private String codTrans;
	private String descTrans;
	private String indpeTrans;
	private String modpTrans;
	private String indDevelop;
	private String indHab;
	
	public Transacs() {
	}

	public Transacs(String codTrans, String descTrans, String indpeTrans,
			String modpTrans,String indDevelop, String indHab) {
		this.codTrans = codTrans;
		this.descTrans = descTrans;
		this.indpeTrans = indpeTrans;
		this.modpTrans = modpTrans;
		this.indDevelop = indDevelop;
		this.indHab = indHab;
	}

	
	public String getIndDevelop() {
		return indDevelop;
	}

	public String getIndHab() {
		return indHab;
	}

	public void setIndHab(String indHab) {
		this.indHab = indHab;
	}

	public void setIndDevelop(String indDevelop) {
		this.indDevelop = indDevelop;
	}

	public String getCodTrans() {
		return this.codTrans;
	}

	public void setCodTrans(String codTrans) {
		this.codTrans = codTrans;
	}

	public String getDescTrans() {
		return this.descTrans;
	}

	public void setDescTrans(String descTrans) {
		this.descTrans = descTrans;
	}

	public String getIndpeTrans() {
		return this.indpeTrans;
	}

	public void setIndpeTrans(String indpeTrans) {
		this.indpeTrans = indpeTrans;
	}

	public String getModpTrans() {
		return this.modpTrans;
	}

	public void setModpTrans(String modpTrans) {
		this.modpTrans = modpTrans;
	}

}
