package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 12, 2012 11:22:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8468748061718645074L;
	private UsuarioId id;
	private String usuaName;
	private String usuaIdenti;
	private String usuaState;
	private String usuaEmail;
	private String usuaTelf;
	private String usuaComment;
	private Date usuaDateini;

	public Usuario() {
	}

	public Usuario(UsuarioId id, String usuaName, String usuaIdenti,
			String usuaState, String usuaEmail, Date usuaDateini) {
		this.id = id;
		this.usuaName = usuaName;
		this.usuaIdenti = usuaIdenti;
		this.usuaState = usuaState;
		this.usuaEmail = usuaEmail;
		this.usuaDateini = usuaDateini;
	}

	public Usuario(UsuarioId id, String usuaName, String usuaIdenti,
			String usuaState, String usuaEmail, String usuaTelf,
			String usuaComment, Date usuaDateini) {
		this.id = id;
		this.usuaName = usuaName;
		this.usuaIdenti = usuaIdenti;
		this.usuaState = usuaState;
		this.usuaEmail = usuaEmail;
		this.usuaTelf = usuaTelf;
		this.usuaComment = usuaComment;
		this.usuaDateini = usuaDateini;
	}

	public UsuarioId getId() {
		return this.id;
	}

	public void setId(UsuarioId id) {
		this.id = id;
	}

	public String getUsuaName() {
		return this.usuaName;
	}

	public void setUsuaName(String usuaName) {
		this.usuaName = usuaName;
	}

	public String getUsuaIdenti() {
		return this.usuaIdenti;
	}

	public void setUsuaIdenti(String usuaIdenti) {
		this.usuaIdenti = usuaIdenti;
	}

	public String getUsuaState() {
		return this.usuaState;
	}

	public void setUsuaState(String usuaState) {
		this.usuaState = usuaState;
	}

	public String getUsuaEmail() {
		return this.usuaEmail;
	}

	public void setUsuaEmail(String usuaEmail) {
		this.usuaEmail = usuaEmail;
	}

	public String getUsuaTelf() {
		return this.usuaTelf;
	}

	public void setUsuaTelf(String usuaTelf) {
		this.usuaTelf = usuaTelf;
	}

	public String getUsuaComment() {
		return this.usuaComment;
	}

	public void setUsuaComment(String usuaComment) {
		this.usuaComment = usuaComment;
	}

	public Date getUsuaDateini() {
		return this.usuaDateini;
	}

	public void setUsuaDateini(Date usuaDateini) {
		this.usuaDateini = usuaDateini;
	}

}
