package ni.gob.minsa.sistema.hibernate.bussines;

// Generated Nov 12, 2012 11:22:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsuarioId generated by hbm2java
 */
public class UsuarioId implements java.io.Serializable {

	
	private static final long serialVersionUID = 6449825612371715265L;
	private String usuaCode;
	private Date usuaDatefin;

	public UsuarioId() {
	}

	public UsuarioId(String usuaCode, Date usuaDatefin) {
		this.usuaCode = usuaCode;
		this.usuaDatefin = usuaDatefin;
	}

	public String getUsuaCode() {
		return this.usuaCode;
	}

	public void setUsuaCode(String usuaCode) {
		this.usuaCode = usuaCode;
	}

	public Date getUsuaDatefin() {
		return this.usuaDatefin;
	}

	public void setUsuaDatefin(Date usuaDatefin) {
		this.usuaDatefin = usuaDatefin;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioId))
			return false;
		UsuarioId castOther = (UsuarioId) other;

		return ((this.getUsuaCode() == castOther.getUsuaCode()) || (this
				.getUsuaCode() != null && castOther.getUsuaCode() != null && this
				.getUsuaCode().equals(castOther.getUsuaCode())))
				&& ((this.getUsuaDatefin() == castOther.getUsuaDatefin()) || (this
						.getUsuaDatefin() != null
						&& castOther.getUsuaDatefin() != null && this
						.getUsuaDatefin().equals(castOther.getUsuaDatefin())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsuaCode() == null ? 0 : this.getUsuaCode().hashCode());
		result = 37
				* result
				+ (getUsuaDatefin() == null ? 0 : this.getUsuaDatefin()
						.hashCode());
		return result;
	}

}
